# Generated by Django 5.2.13 on 2026-05-05 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('number_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('max_operand', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('question_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('allow_negative_intermediate', models.BooleanField(default=False)),
                ('duration_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '测试配置',
                'verbose_name_plural': '测试配置',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_seconds', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('correct_questions', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='practice.testconfig')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('expression', models.CharField(max_length=255)),
                ('correct_answer', models.IntegerField()),
                ('user_answer', models.IntegerField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.testattempt')),
            ],
            options={
                'verbose_name': '题目明细',
                'verbose_name_plural': '题目明细',
                'ordering': ('position',),
                'unique_together': {('attempt', 'position')},
            },
        ),
    ]
